# Generated by Django 4.0.6 on 2022-12-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Home',
        ),
    ]
